### ISSUE TITLE
check if dataset exists when user supplies specific dataset ID

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#363]
now the pipeline fails with a useless message by the old ORM. Probably SQLAlchemy would handle the error better.

error:
```
INFO:tkp.steps.persistence:added dataset with ID 176
INFO:tkp.steps.persistence:Storing images
ERROR:tkp.db:Query failed: insert or update on table "skyregion" violates foreign key constraint "skyregion_dataset_fkey" 
DETAIL:  Key (dataset)=(176) is not present in table "dataset".
CONTEXT:  SQL statement "INSERT INTO skyregion
      (dataset
      ,centre_ra
      ,centre_decl
      ,xtr_radius
      ,x
      ,y
      ,z
      ) 
    SELECT idataset
          ,icentre_ra
          ,icentre_decl
          ,ixtr_radius
          ,cart.x
          ,cart.y
          ,cart.z
    FROM (SELECT *
          FROM cartesian(icentre_ra,icentre_decl)
          ) cart
      RETURNING id" 
PL/pgSQL function "getskyrgn" line 27 at SQL statement
PL/pgSQL function "insertimage" line 10 at assignment
. Query:     SELECT insertImage(176
                      ,658
                      ,123924255.371
                      ,1953125.0
                      ,2013-02-10 07:00:07
                      ,0.017816397349
                      ,0.0146109188928
                      ,97.5848388672
                      ,-0.00555555555556
                      ,0.00555555555556
                      ,/scratch/er/L89663_SAP002_BAND00.MS.dppp.img.restored.corr
                      ,238.125
                      ,50.941028
                      ,1.38888888889
                      )
    .
Traceback (most recent call last):
  File "/home/gijs/Work/tkp/tkp/bin/tkp-manage.py", line 10, in <module>
    tkp.management.main()
  File "/home/gijs/Work/tkp/tkp/management.py", line 371, in main
    args.func(args)
  File "/home/gijs/Work/tkp/tkp/management.py", line 237, in run_job
    run(args.name, monitor_coords)
  File "/home/gijs/Work/tkp/tkp/main.py", line 107, in run
    persistence)
  File "/home/gijs/Work/tkp/tkp/steps/persistence.py", line 154, in master_steps
    image_ids = store_images(metadatas, extraction_radius_pix, dataset_id)
  File "/home/gijs/Work/tkp/tkp/steps/persistence.py", line 112, in store_images
    db_image = Image(data=metadata, dataset=dataset)
  File "/home/gijs/Work/tkp/tkp/db/orm.py", line 395, in __init__
    self._init_data()
  File "/home/gijs/Work/tkp/tkp/db/orm.py", line 182, in _init_data
    self.id
  File "/home/gijs/Work/tkp/tkp/db/orm.py", line 195, in __getattr__
    raise AttributeError("attribute '%s' not found" % name)
AttributeError: attribute 'id' not found
```

moved from lofar issue tracker:
https://support.astron.nl/lofar_issuetracker/issues/5788

**Comment by AntoniaR** [comment]
Unclear if this is still an issue so would be good to test with the latest version.
