### ISSUE TITLE
Dropping "island" in pyse causes database error: INSERT has more target columns than expressions

### ISSUE THREAD

**Issue by mkuiack** [transientskp/tkp#466]
If a source (island) is not fit properly and dropped from island_list in image._pyse it results in a database error 

```
Traceback (most recent call last):
  File "./trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/scratch/mkuiack/pipeline/tkp/management.py", line 323, in main
    args.func(args)
  File "/scratch/mkuiack/pipeline/tkp/management.py", line 223, in run_job
    run(args.name, monitor_coords)
  File "/scratch/mkuiack/pipeline/tkp/main.py", line 147, in run
    dbgen.insert_extracted_sources(image.id, results.sources, 'blind')
  File "/scratch/mkuiack/pipeline/tkp/db/general.py", line 345, in insert_extracted_sources
    commit=True)
  File "/scratch/mkuiack/pipeline/tkp/db/__init__.py", line 20, in execute
    return database.execute(query, parameters=parameters, commit=commit)
  File "/scratch/mkuiack/pipeline/tkp/db/database.py", line 183, in execute
    cursor = self.connection.execute(query, parameters)
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 906, in execute
    return self._execute_text(object, multiparams, params)
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1054, in _execute_text
    statement, parameters
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/var/lib/jenkins/workspace/tkp-monetdb_PR/virtualenv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) INSERT has more target columns than expressions
LINE 31:   ,ff_runcat
            ^
 [SQL: 'INSERT INTO extractedsource\n  (ra\n  ,decl\n  ,ra_fit_err\n  ,decl_fit_err\n  ,f_peak\n  ,f_peak_err\n  ,f_int\n  ,f_int_err\n  ,det_sigma\n  ,semimajor\n  ,semiminor\n  ,pa\n  ,ew_sys_err\n  ,ns_sys_err\n  ,error_radius\n  ,fit_type\n  ,chisq\n  ,reduced_chisq\n  ,ra_err\n  ,decl_err\n  ,uncertainty_ew\n  ,uncertainty_ns\n  ,image\n  ,zone\n  ,x\n  ,y\n  ,z\n  ,racosdecl\n  ,extract_type\n  ,ff_runcat\n  ,ff_monitor\n  )\nVALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)\n'] [parameters: (294.16451347128049, 27.371495771652469, 0.16200695264166143, 0.13462401518994227, 33890870652.296204, 1752315416.3261425, 614353601814.92456, 33483672126.964382, 17.401407016368708, 8915.100742922656, 7286.650022678615, 62.550845275859878, 10, 10, 747.6790548080029, 1, 0.16203714671432262, 0.13465266991502442, 0.20770720150859737, 0.20770720150859737, 5499, 27, 0.3635280307390157, -0.8102283071995503, 0.45975804623689237, 261.23109628911521, 0, None, None)]
```

**Comment by gijzelaerr** [comment]
I think your local fix for #465 is not correct, not sure what you did. But I think the arguments you give to `insert_extracted_sources` is invalid, maybe a None value in the results list.

I'm closing this issue, since I think this is not a problem with the current code but with your uncommitted and unfinished fix :)
