### ISSUE TITLE
TraP is crashing when trap-manage.py is run

### ISSUE THREAD

**Issue by ycendes** [transientskp/tkp#503]
I was tipped off to this issue yesterday by our bachelor student, Vincent, who does not have an account here but told me he was unable to run TraP as he previously had.  I did a test run myself which also failed, and we both get the following error-

```
ycendes@struis:/scratch/ycendes/aartfaac/candidate/candidate-pipeline$ trap-manage.py run cendes-candidate-SB003
running job 'cendes-candidate-SB003'
Traceback (most recent call last):
  File "/soft/trap/r3.1.0/bin/trap-manage.py", line 5, in <module>
    pkg_resources.run_script('tkp==3.1.0', 'trap-manage.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/soft/trap/r3.1.0/lib/python2.7/site-packages/tkp-3.1.0-py2.7.egg/EGG-INFO/scripts/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/soft/trap/r3.1.0/lib/python2.7/site-packages/tkp-3.1.0-py2.7.egg/tkp/management.py", line 329, in main
    args.func(args)
  File "/soft/trap/r3.1.0/lib/python2.7/site-packages/tkp-3.1.0-py2.7.egg/tkp/management.py", line 227, in run_job
    run(args.name, monitor_coords)
  File "/soft/trap/r3.1.0/lib/python2.7/site-packages/tkp-3.1.0-py2.7.egg/tkp/main.py", line 45, in run
    use_colorlog=pipe_config.logging.colorlog
  File "/soft/trap/r3.1.0/lib/python2.7/site-packages/tkp-3.1.0-py2.7.egg/tkp/utility/__init__.py", line 47, in __getattr__
    raise AttributeError(msg % key)
AttributeError: can't find colorlog, please check your settings file
```

**Comment by AntoniaR** [comment]
This is a TraP 3.1 bug. The quick fix is to use release 3.0 instead ( `. /soft/trap/r3.0/init.sh` and not `. /soft/trap/latest/init.sh`) and then it runs fine. However, can you check this is actually a 3.1 bug and not a mismatch somewhere in versions used to run the pipeline? Make a new TraP project folder and a new database, then try again.

**Comment by gijzelaerr** [comment]
this is a easy fix, will do tomorrow. 3.1 uses a new formatting module for
colorizing logging output, which is not yet installed on struis.

This is not a bug with TraP but a struis deployment issue. For now just use
3.0.

2016-04-07 12:19 GMT+02:00 Antonia Rowlinson <notifications@github.com>:

> This is a TraP 3.1 bug. The quick fix is to use release 3.0 instead ( .
> /soft/trap/r3.0/init.sh and not . /soft/trap/latest/init.sh) and then it
> runs fine. However, can you check this is actually a 3.1 bug and not a
> mismatch somewhere in versions used to run the pipeline? Make a new TraP
> project folder and a new database, then try again.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/transientskp/tkp/issues/503#issuecomment-206799252>
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by gijzelaerr** [comment]
ok this is not a bug. 

as you can read in the TraP 3.1 release notes, you need to add a colorlog option to your settings file:

https://github.com/transientskp/tkp/releases

Please read the release notes before you switch version.

**Comment by timstaley** [comment]
This was not helped by a typo in the release notes, but it's been fixed now https://github.com/transientskp/tkp/commit/05f9ab65eee4d821597b4635d9a517f81c8ee084.
