### ISSUE TITLE
streaming mode gives harmless database errors

### ISSUE THREAD

**Issue by gijzelaerr** [transientskp/tkp#536]
TraP gives an error in streaming mode, see below. Oddly enough Trap just continues running and everything works fine. Still we should find out what is causing this. The errors always come from the same threads/processes, one is the sync manager for multiprocessing and the other looks like is a process that uses astropy (using threads). This probably can be solved my making sure no threading is happening before forking (multiprocessing).  This is related to issue https://github.com/transientskp/tkp/issues/519, although now TraP is not crashing anymore.

```
16:35:34 ERROR sqlalchemy.engine.default: exception raised: <class 'psycopg2.OperationalError'>, SSL SYSCALL error: EOF detected

16:35:34 ERROR sqlalchemy.pool.NullPool: Exception during reset or similar
Traceback (most recent call last):
  File "/home/gijs/Work/tkp/.virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/home/gijs/Work/tkp/.virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/home/gijs/Work/tkp/.virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 424, in do_rollback
    dbapi_connection.rollback()
OperationalError: SSL SYSCALL error: EOF detected
```

```
16:35:34 ERROR sqlalchemy.pool.NullPool: Exception during reset or similar
Traceback (most recent call last):
  File "/home/gijs/Work/tkp/.virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 636, in _finalize_fairy
    fairy._reset(pool)
  File "/home/gijs/Work/tkp/.virtualenv/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 776, in _reset
    pool._dialect.do_rollback(self)
  File "/home/gijs/Work/tkp/.virtualenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 424, in do_rollback
    dbapi_connection.rollback()
OperationalError: SSL error: decryption failed or bad record mac
```

**Comment by AntoniaR** [comment]
Unclear if this is still an issue so would be good to test with the latest version.
