### ISSUE TITLE
ValueError: Unknown string format when parsing pysquasher fits header?  

### ISSUE THREAD

**Issue by mkuiack** [transientskp/tkp#537]
```bash
/scratch/mkuiack/16SB_integrated/201609070340_16/20160907093650UTC_S307.5_I16x1_W6_A1.5.fits
*************************
15:35:22 INFO tkp.main: dataset run201609070340/ contains 17268 images
15:35:22 INFO root: storing copies in image cache is disabled
Traceback (most recent call last):
  File "/scratch/mkuiack/trapvenv/bin/trap-manage.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/scratch/mkuiack/tkp/tkp/bin/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/scratch/mkuiack/tkp/tkp/management.py", line 329, in main
    args.func(args)
  File "/scratch/mkuiack/tkp/tkp/management.py", line 227, in run_job
    run(args.name, monitor_coords)
  File "/scratch/mkuiack/tkp/tkp/main.py", line 400, in run
    run_batch(job_name, job_dir, pipe_config, job_config, runner, dataset_id)
  File "/scratch/mkuiack/tkp/tkp/main.py", line 370, in run_batch
    sorting_metadata = get_metadata_for_sorting(runner, image_paths)
  File "/scratch/mkuiack/tkp/tkp/main.py", line 268, in get_metadata_for_sorting
    results = runner.map("get_metadata_for_ordering", nested_img)
  File "/scratch/mkuiack/tkp/tkp/distribute/__init__.py", line 42, in map
    return self.module.map(func, iterable, args)
  File "/scratch/mkuiack/tkp/tkp/distribute/serial/__init__.py", line 3, in map
    x = [func(i, *arguments) for i in iterable]
  File "/scratch/mkuiack/tkp/tkp/distribute/serial/tasks.py", line 45, in get_metadata_for_ordering
    for a in tkp.steps.persistence.get_accessors(images):
  File "/scratch/mkuiack/tkp/tkp/steps/persistence.py", line 160, in get_accessors
    accessor = tkp.accessors.open(image)
  File "/scratch/mkuiack/tkp/tkp/accessors/__init__.py", line 75, in open
    return Accessor(path, *args, **kwargs)
  File "/scratch/mkuiack/tkp/tkp/accessors/requiredatts.py", line 61, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/scratch/mkuiack/tkp/tkp/accessors/fitsimage.py", line 30, in __init__
    self.taustart_ts, self.tau_time = self.parse_times()
  File "/scratch/mkuiack/tkp/tkp/accessors/fitsimage.py", line 212, in parse_times
    start = self.parse_start_time()
  File "/scratch/mkuiack/tkp/tkp/accessors/fitsimage.py", line 248, in parse_start_time
    start = dateutil.parser.parse(header['date-obs'])
  File "/scratch/mkuiack/trapvenv/local/lib/python2.7/site-packages/dateutil/parser.py", line 1164, in parse
    return DEFAULTPARSER.parse(timestr, **kwargs)
  File "/scratch/mkuiack/trapvenv/local/lib/python2.7/site-packages/dateutil/parser.py", line 555, in parse
    raise ValueError("Unknown string format")
ValueError: Unknown string format
```

fits files are in: 
struis:/scratch/mkuiack/16SB_integrated/201609070340_16/

```bash
(trapvenv)mkuiack@struis:/scratch/mkuiack/tkp$ git status 
On branch aartfaac-stream
Your branch is up-to-date with 'origin/aartfaac-stream'.
```

TraP ran in batch mode, multiproc and serial both failed.

**Comment by gijzelaerr** [comment]
did you try 4.0rc1 ?

**Comment by gijzelaerr** [comment]
just verified, same problem with 4.0rc1. BTW, no need to use that branch anymore, please use 4.0rc1.

**Comment by gijzelaerr** [comment]
where did you get this fits file from?  observation date is `2016-09-07T09:36:50.765(UTC)` which is indeed a format we have not encountered before.

**Comment by mkuiack** [comment]
These files are the new Pysquasher outputs.

**Comment by gijzelaerr** [comment]
ok then that is the problem, @Error323 made up a YetAnotherFitsFileFormatSpecification. I recommend we stick with LOFAR fits file format. Closing this issue, this should be fixed on the pysquasher side.

**Comment by Error323** [comment]
I will update pysquasher to respect the standard described at https://archive.stsci.edu/fits/fits_standard/node40.html#s:dhist
