### ISSUE TITLE
Delete dataset rejection table error

### ISSUE THREAD

**Issue by ajstewart** [transientskp/tkp#556]
A different error from before - attempting to delete a (large) dataset I ran into the following error. Probably not vital but thought I'd record it here.

```
(trap) ada:~/ada2/CHILES/ada-trap-chiles-1min$ trap-manage.py deldataset 6

This script will delete dataset 6 with these settings:

        engine:     postgresql
        database:   CHILES_1min
        user:       aste7152
        password:   aste7152
        host:       localhost
        port:       5432

Are you sure you want to delete dataset 6? [y/N]: y
/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
Traceback (most recent call last):
  File "/suphys/aste7152/.conda/envs/trap/bin/trap-manage.py", line 10, in <module>
    tkp.management.main()
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/tkp/management.py", line 375, in main
    args.func(args)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/tkp/management.py", line 276, in deldataset
    db.session.commit()
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 447, in _prepare_impl
    self.session.flush()
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2254, in flush
    self._flush(objects)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2380, in _flush
    transaction.rollback(_capture_exception=True)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2344, in _flush
    flush_context.execute()
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 386, in execute
    n.execute_aggregate(self, set_)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 489, in execute_aggregate
    self.execute(uow)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 593, in execute
    uow
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 265, in delete_obj
    cached_connections, mapper, table, delete)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 1028, in _emit_delete_statements
    c = connection.execute(statement, del_objects)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
    context)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1170, in _execute_context
    context)
  File "/suphys/aste7152/.conda/envs/trap/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 683, in do_executemany
    cursor.executemany(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) update or delete on table "image" violates foreign key constraint "rejection_image_fkey" on table "rejection"
DETAIL:  Key (id)=(8963) is still referenced from table "rejection".
 [SQL: 'DELETE FROM image WHERE image.id = %(id)s'] [parameters: ({'id': 8837}, {'id': 8838}, {'id': 8839}, {'id': 8840}, {'id': 8841}, {'id': 8842}, {'id': 8843}, {'id': 8844}  ... displaying 10 of 8233 total bound parameter sets ...  {'id': 17068}, {'id': 17069})] (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by AntoniaR** [comment]
Solution here: https://github.com/transientskp/tkp/issues/555#issuecomment-884835694

So closing this issue
